### ISSUE TITLE
Miner Node H/s Rate Not Right

### ISSUE THREAD

**Issue by jzencore** [cubedro/eth-netstats#116]
In eth-netstats/public/js/filters.js, hashrateFilter function, the hashes or unit is off by a factor of 1000. Since the base unit of hashes reported is KH/s and not H/s, hashes should be set to hashes * 1000 prior to hashes conditional logic evaluation for results and units.

**Comment by cubedro** [comment]
Hashrate should be reported in H/s according to the specs: https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_hashrate

Geth is reporting KH/s which is not correct. It's pending to be fixed in geth.

**Comment by cubedro** [comment]
https://github.com/ethereum/go-ethereum/issues/923
