### ISSUE TITLE
Page latency keeps increasing forever

### ISSUE THREAD

**Issue by drupalnomad** [cubedro/eth-netstats#207]
If I leave https://stats.ethdev.com/ open in chrome the PAGE LATENCY will keep increasing continuously. After just a short time it will be 80s behind. Is it possible for this to be fixed?

Thanks!

**Comment by cubedro** [comment]
Do you also run ethereum? I noticed when running geth if the cpu is in high load (300% geth) the browser can't keep up with everything it has to show and it falls behind. Can you please confirm this is the case?

**Comment by drupalnomad** [comment]
Yes you are right. If chrome doesn't have enough CPU time it falls behind. Is it possible for the page to be able to handle this situation better?
