### ISSUE TITLE
Consider making publication of a node's IP address optional

### ISSUE THREAD

**Issue by jzencore** [cubedro/eth-netstats#241]
Currently, each node listed on the netstats page has its IP address published.  Some folks might like to have their nodes listed but not necessarily their IP addresses published on the world wide web.  Please consider making publication of the IP address a per node config option.

**Comment by jmiehau** [comment]
:+1:

**Comment by cubedro** [comment]
Fixed in 99e74187acde0525abab56d8282c41225641d1a4
