### ISSUE TITLE
ng-cloak

### ISSUE THREAD

**Issue by debris** [cubedro/eth-netstats#245]
ng-cloak again... :)

<img width="1482" alt="screen shot 2015-08-05 at 10 17 52" src="https://cloud.githubusercontent.com/assets/2613714/9081303/6ec4a5c2-3b5b-11e5-9569-68be098cc1df.png">

**Comment by cubedro** [comment]
can't be. I think something didn't load correctly. I tested it and couldn't replicate. Can you please confirm?

**Comment by debris** [comment]
maybe something has cached... I will close and reopen if it occurs again.
