### ISSUE TITLE
stats.ethdev on error on Chrome - OSX

### ISSUE THREAD

**Issue by jmiehau** [cubedro/eth-netstats#251]
![captura de pantalla 2015-08-08 a las 1 21 31](https://cloud.githubusercontent.com/assets/4571693/9147748/decc9bb0-3d6b-11e5-9c6d-4f1fd86b7f83.png)

I am on Chrome Version 43.0.2357.124 (64-bit)

**Comment by cubedro** [comment]
js and css files were not loaded. Does this happen anymore?

**Comment by jmiehau** [comment]
:+1: it works!
