### ISSUE TITLE
"Private" EthStat behind proxy - empty portal

### ISSUE THREAD

**Issue by wawrzek** [cubedro/eth-netstats#290]
I have ethstats for local cluster running on port 3000. Now I try to add a proxy on port 80 it can be visible without opening extra firewall holes.

Currently I'm trying Apache. With following configuration I see full, but empty interface.  Any hints welcome. 
```

ProxyRequests off
<Proxy *>
    Require all granted
</Proxy>
ProxyPass / http://localhost:3000/
ProxyPassReverse /  http://localhost:3000/
<Location />
    Require all granted
</Location>
```

**Comment by cubedro** [comment]
The proxy has to support Connection Upgrade. Here's a [gist](https://gist.github.com/cubedro/81fd017886e3cc14d302) of the nginx config I used for ethstats.net

**Comment by wawrzek** [comment]
Thanks for response. After small modification (replacing 'root') it works
for me.

Wawrzek

On 7 April 2016 at 20:11, Marian OANCΞA <notifications@github.com> wrote:

> The proxy has to support Connection Upgrade. Here's a gist
> <https://gist.github.com/cubedro/81fd017886e3cc14d302> of the nginx
> config I used for ethstats.net
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/cubedro/eth-netstats/issues/290#issuecomment-207053564>
>



-- 
Dr  Wawrzyniec Niewodniczański    or Wawrzek for short
  PhD in Quantum Chemistry  & MSc in Molecular Engineering
   WWW: http://wawrzek.name E-MAIL: jobs@wawrzek.name
      Linux User #177124
