### ISSUE TITLE
netstats.min.js does not exist

### ISSUE THREAD

**Issue by hievan2016** [cubedro/eth-netstats#291]
No content is shown in  http://localhost:3000 because netstats.min.js does not exist,
this file is used in following files, is anything wrong with the code? 

Gruntfile.js:209:                               dest: 'dist/js/netstats.min.js',
Gruntfile.js:239:                               dest: 'dist-lite/js/netstats.min.js',
src/views/layout.jade:13:    script(src="/js/netstats.min.js")
src-lite/views/layout.jade:13:    script(src="/js/netstats.min.js")

**Comment by cubedro** [comment]
You should run `grunt build` or `grunt lite` (for building the lite version) before launching netstats.

**Comment by jazzuc** [comment]
@cubedro I ran into the same issue which led me here.  The issue might be that this really old wiki article (linked below) skips the grunt steps.  It would be great if it could be updated to say "Read the README.md" file after cloning the repo :)
https://github.com/ethereum/go-ethereum/wiki/Setting-up-monitoring-on-local-cluster
