### ISSUE TITLE
SSL Certificate has expired

### ISSUE THREAD

**Issue by jerkly** [cubedro/eth-netstats#310]
<img width="484" alt="screen shot 2017-07-24 at 01 13 44" src="https://user-images.githubusercontent.com/8193821/28503367-ea705db8-700d-11e7-8764-b3dde3e1d9de.png">

**Comment by mikeyb** [comment]
Also, should be able to drop in the cron command to update that automatically, though you may have done that already and just need to bounce web server

**Comment by jerkly** [comment]
Closed as fixed.
