### ISSUE TITLE
Questions about ethstats

### ISSUE THREAD

**Issue by zulhfreelancer** [cubedro/eth-netstats#335]
Hi,

I have 3 questions here about ethstats. I'm currently using ethstats for my PoA private blockchain and I like it.

![ethstats](https://user-images.githubusercontent.com/3416976/48555813-3823e500-e91d-11e8-8d9c-ea9363f3bf8b.png)

But here I have 3 questions.

1. How do I remove the `offline` nodes from the list?
2. Why the colors sometimes change between red, orange and green? What does it mean for each color?
3. Is it normal that sometimes the nodes show `0` peers or lower than it should be? I noticed that my nodes somestimes show `0` and `1`. I'm expecting `3` because I have 3 sealnodes.

FYI, I'm using Puppeth to provision this cluster and ethstats.

Thank you.

**Comment by AyushyaChitransh** [comment]
> How do I remove the offline nodes from the list?

The offline nodes go away on their own, but if you want to remove manually, restarting ethstats site would help it. You can control how long inactive nodes stay on screen by adjusting the MAX_INACTIVE_TIME variable at https://github.com/cubedro/eth-netstats/blob/master/lib/node.js#L6

> Why the colors sometimes change between red, orange and green? What does it mean for each color?

Red represents danger, orange means its not in best state, green means it is in best shape. We usually take red colors as a sign of something went wrong. More information regarding the relation of color and value of different parameters can be found at [web-app/.meteor/local/build/programs/web.browser/app/client/js/templateHelpers.js](https://github.com/cubedro/eth-netstats/blob/5d3ed04c55314f05ce0f9b7fa3dfa8e4c7860720/web-app/.meteor/local/build/programs/web.browser/app/client/js/templateHelpers.js)

> Is it normal that sometimes the nodes show 0 peers or lower than it should be? I noticed that my nodes sometimes show 0 and 1. I'm expecting 3 because I have 3 sealnodes.

This is the number of nodes that one node is connected to. Usually nodes discover other nodes by themselves, but in case if I want to add a node manually from my end I would be connecting them manually. [Connecting to the network](https://github.com/ethereum/go-ethereum/wiki/Connecting-to-the-network) describes in detail how nodes can be connected to each other.

**Comment by zulhfreelancer** [comment]
Thank you @AyushyaChitransh for the answer. Really appreciate it!
