### ISSUE TITLE
Improvement suggestion: Add nodes current hash rate to the table.

### ISSUE THREAD

**Issue by alexvandesande** [cubedro/eth-netstats#84]
It would be a useful way for a user to know how his machine compares to others. Knowing the difficulty is 9 million and their hash rate is 710 doesn't help most users as those numbers are very different. Knowing the hash rate of the top nodes, or the average hash rate of nodes in the network, could be better for a new user to easily measure himself against most.

**Comment by cubedro** [comment]
Fixed in #92
